/*************************************************************
***
***  Name       :  ddl_sla.sql 
***  purpose    :  To identify and categerize the list of 
                   Service Level Agreements. 
***  Dependency :  Down stream dependency with User or request Table. 
***  
***
*** Data Model: https://drawsql.app/teams/sayam-team/diagrams/saayam-arch
***
*** Created on   : 06/27/2023 
*** Created By   : 
*** Last Updatee :
*** Last update by : 
*** change comments: 
***
***
******************************************************************/


drop table if exists sla ;

create table if not exists sla
( 
    sla_id           integer generated by default as identity
   ,sla_typ_dsc      varchar(30) not null 
   ,no_of_cust_impct integer 
   ,eta_in_hrs       integer  not null
   ,cre_dt           date default current_date 
   ,cre_by           varchar(30) default 'SYSTEM' 
   ,upd_dt           date  
   ,upd_by           varchar(30) 
   ,CONSTRAINT  uk_sla_sla_id  unique(sla_id) 
 );
 
 