CREATE TABLE IF NOT EXISTS virginia_dev_saayam_rdbms.req_comments (
    -- comment_id is the primary key, using a BIGINT and auto-generated identity (like SERIAL)
    comment_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    req_id VARCHAR(255) NOT NULL,
    commenter_id VARCHAR(255) NOT NULL,
    comment_desc TEXT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    last_updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    isdeleted BOOLEAN DEFAULT FALSE,
    CONSTRAINT fk_req_comment_request
        FOREIGN KEY (req_id) 
        REFERENCES virginia_dev_saayam_rdbms.request (req_id) 
        ON UPDATE CASCADE 
        ON DELETE CASCADE,    
    CONSTRAINT fk_req_comment_user
        FOREIGN KEY (commenter_id) 
        REFERENCES virginia_dev_saayam_rdbms.users (user_id) 
        ON UPDATE CASCADE 
        ON DELETE CASCADE
);

-- Index for efficient lookup by request ID
CREATE INDEX IF NOT EXISTS idx_req_comment_req_id
    ON virginia_dev_saayam_rdbms.req_comments (req_id);

-- Index for efficient lookup by commenter ID
CREATE INDEX IF NOT EXISTS idx_req_comment_commenter_id
    ON virginia_dev_saayam_rdbms.req_comments (commenter_id);

-- Index for filtering out soft-deleted comments
CREATE INDEX IF NOT EXISTS idx_req_comment_isdeleted
    ON virginia_dev_saayam_rdbms.req_comments (isdeleted);
