/*************************************************************
***
***  Name       :  region.sql 
***  purpose    :  to retain the list of regions currently serving.
***                
***  Dependency :  country 
***  
***
*** Data Model: https://drawsql.app/teams/sayam-team/diagrams/saayam-arch
*** Code Repo  : https://github.com/saayam-for-all/database
***
*** Created on   : 06/29/2023 
*** Created By   : 
*** Last Updatee :
*** Last update by : 
*** change comments: initutive column name changes 
***
***
******************************************************************/

drop table if exists region ;

create table if not exists region
( 
    region_id     integer generated by default AS identity
   ,region_nm     varchar(30)	 not null
   ,created_dt    date default current_date 
   ,created_by    varchar(30) default 'SYSTEM' 
   ,last_update_by varchar(30)
   ,last_update    date  
 ,CONSTRAINT  uk_region_regn_id  unique(region_id) 
 );