/*************************************************************
***
***  Name       :  priority.sql 
***  purpose    :  To identigy and categorize priority of the requests. 
***  Depemdency :  
***  
***
*** Data Model: https://drawsql.app/teams/sayam-team/diagrams/saayam-arch
***
*** Created on   : 06/29/2023 
*** Created By   : 
*** Last Updatee :
*** Last update by : 
*** change comments: 
***
***
******************************************************************/

drop table if exists priority ;

create table if not exists priority
( 
    prty_id    integer generated by default AS identity
   ,prty_typ   varchar(10)	 not null 
   ,prty_desc  varchar(30)  not null 
   ,cre_dt      date default current_date 
   ,cre_by      varchar(30) default 'SYSTEM' 
   ,upd_dt     date  
   ,upd_by  varchar(30) 
   ,CONSTRAINT  uk_priority_prty_id  unique(prty_id) 
 );