/*************************************************************
***
***  Name       :  action.sql 
***  purpose    :  categorize the list of action served by the user
***                volunteer or donars
***  Depemdency :  
***  
***
*** Data Model: https://drawsql.app/teams/sayam-team/diagrams/saayam-arch
*** Code Repo : https://github.com/saayam-for-all/database
***
*** Created on   : 06/29/2023 
*** Created By   : 
*** Last Update : 04/14/2024 
*** Last update by : 
*** change comments: Initutive column name changes 
***
***
******************************************************************/

drop table if exists action ;

create table if not exists action
( 
    action_id    integer generated by default AS identity
   ,action_desc  varchar(30)	 not null 
   ,created_dt   date default current_date 
   ,created_by   varchar(30) default 'SYSTEM' 
   ,last_upd_by  varchar(30)
   ,last_upd_dt  date
   ,CONSTRAINT  uk_action_actn_id  unique(action_id) 
 );