/*************************************************************
***
***  Name       :  priority.sql 
***  purpose    :  To identigy and categorize priority of the requests. 
***  Depemdency :  
***  
***
*** Data Model: https://drawsql.app/teams/sayam-team/diagrams/saayam-arch
*** Code Repo  : https://github.com/saayam-for-all/database/tree/main/ddl
***
*** Created on   : 06/29/2023 
*** Created By   : 
*** Last Update : 04/14/2024
*** Last update by : 
*** change comments: Initutive Column Changes
***
***
******************************************************************/

drop table if exists priority ;

create table if not exists priority
( 
    priority_id     integer generated by default AS identity
   ,priority_typ    varchar(10)	 not null 
   ,priority_desc   varchar(30)  not null
   ,created_by      varchar(30) default 'SYSTEM'    
   ,created_dt      date default current_date 
   ,last_update_by  varchar(30) 
   ,lapst_update_dt date  
   
   ,CONSTRAINT  uk_priority_prty_id  unique(priority_id) 
 );