/*************************************************************
***
***  Name       :  cntry.sql 
***  purpose    :  categorize the list of countries currently serving
***  Depemdency :  region , states 
***  
***
*** Data Model: https://drawsql.app/teams/sayam-team/diagrams/saayam-arch
***
*** Created on   : 06/29/2023 
*** Created By   : 
*** Last Updatee :
*** Last update by : 
*** change comments: 
***
***
******************************************************************/
drop table if exists cntry ;

create table if not exists cntry
( 
    cntry_id    integer generated by default AS identity
   ,cntry_ph_cd varchar(5) not null 
   ,cntry_nm   varchar(30)	 not null 
   ,regn_id     integer  not null 
   ,cre_dt      date default current_date 
   ,cre_by      varchar(30) default 'SYSTEM' 
   ,lst_upd     date  
   ,lst_upd_by  varchar(30) 
   ,CONSTRAINT  uk_cntry_cntry_id  unique(cntry_ph_cd)
   ,CONSTRAINT  fk_regn_regn_id FOREIGN KEY (regn_id) REFERENCES region(regn_id)    
 );