name: Database Pipeline

on:
  push:
    branches:
      - main
      - feature/database-cicd-pipeline

  pull_request:
    branches:
      - main

jobs:
  validate-sql-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify repository structure
        run: |
          echo "Checking repository structure..."

          if [ ! -d "ddl" ]; then
            echo "ddl folder not found"
            exit 1
          fi

          if [ ! -d "dml" ]; then
            echo "dml folder not found"
            exit 1
          fi

          echo "Repository structure verified."

      - name: List DDL files
        run: find ddl -name "*.sql"

      - name: List DML files
        run: find dml -name "*.sql"
        
      - name: Check SQL files are not empty
        run: |
          echo "Checking SQL files..."

          empty_files=$(find ddl dml -type f -name "*.sql" -empty)

          if [ -n "$empty_files" ]; then
            echo "The following SQL files are empty:"
            echo "$empty_files"
            exit 1
          fi

          echo "All SQL files contain content."